language: elixir
elixir:
  - 1.9
otp_release:
  - 22.0
sudo: false
env:
  global:
    - ELIXIR_ASSERT_TIMEOUT=2000
addons:
  postgresql: '11.5'
env:
  - MIX_ENV=dev
before_script:
  - cd apps/instacook
  - mix ecto.create