language: elixir
elixir:
  - 1.9
otp_release:
  - 22.0
sudo: false
env:
  global:
  - ELIXIR_ASSERT_TIMEOUT=2000
services:
  - postgresql
postgres:
  adapter: postgresql
  database: instacook_dev
  username: postgres
  password: postgres
  hostname: localhost
  pool_size: 10
env:
  - MIX_ENV=dev
before_script:
  - psql -c "CREATE DATABASE instacook_dev;" -U postgres
  - cd apps/instacook/ && mix ecto.create